### ISSUE TITLE
ValueError: pins 34~39 do not have pull-up or pull-down circuitry

### ISSUE THREAD

**Issue by Pitel** [hardkernel/ODROID-GO-MicroPython#2]
```
Traceback (most recent call last):
  File "boot.py", line 5, in <module>
  File "odroid_go/__init__.py", line 1, in <module>
  File "odroid_go/odroid_go.py", line 75, in <module>
  File "odroid_go/odroid_go.py", line 12, in __init__
  File "odroid_go/odroid_go.py", line 25, in _init_buttons
  File "odroid_go/utils/button/button.py", line 43, in __init__
ValueError: pins 34~39 do not have pull-up or pull-down circuitry
MicroPython ESP32_LoBo_v3.2.20 - 2018-06-28 on ESP32&psRAM board with ESP32
```

Using [MicroPython.fw](https://github.com/OtherCrashOverride/MicroPython_ESP32_psRAM_LoBo-odroid-go/releases/tag/20180726) from @OtherCrashOverride

**Comment by Pitel** [comment]
`esp32-20181005-v1.9.4-631-g338635ccc.bin` works, so probably bug in [MicroPython.fw](https://github.com/OtherCrashOverride/MicroPython_ESP32_psRAM_LoBo-odroid-go/releases/tag/20180726) from @OtherCrashOverride

**Comment by leeseungcheol** [comment]
I see. We will also try to pull-up and pull-down on the MicroPython.fw.
Thank you.

**Comment by OtherCrashOverride** [comment]
> ValueError: pins 34~39 do not have pull-up or pull-down circuitry

The ESP32 hardware does not have internal pull up/down capability on some IO pins.  On the ODROID-GO, these pins have external resistors where needed.  It is considered an error to try to set a pull up/down on a pin that is not capable of it.
